---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
    - name: cilium-bgp
      localASN: 64513
      peers:
        - name: "router"
          peerASN: 64512
          peerAddress: "192.168.2.1"
          peerConfigRef:
            name: "cilium-peer"
