---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "local-pool"
  labels:
    bgp: public
spec:
  blocks:
    - start: "192.168.2.250"
      stop: "192.168.2.254"
  serviceSelector:
    matchExpressions:
      - { key: bgp, operator: In, values: [public] }
