---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab-l2-advertisement
  namespace: kube-system
spec:
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
    - "wlan0"
