---
k8sServiceHost: "192.168.2.100"
k8sServicePort: 6443
kubeProxyReplacement: true

envoy:
  enabled: true

operator:
  replicas: 1
  rollOutPods: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - hubble.lan
      pathType: ImplementationSpecific
