---
k8sServiceHost: "192.168.2.100"
k8sServicePort: 6443
kubeProxyReplacement: true

envoy:
  enabled: true

operator:
  replicas: 1
  rollOutPods: true

ingressController:
  enabled: true
  default: true
  service:
    externalTrafficPolicy: Local

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: "cilium"
      hosts:
        - hubble-ui.k8s.lan

l2announcements:
  enabled: true

bgpControlPlane:
  enabled: true

externalIPs:
  enabled: true
