---
k8sServiceHost: "192.168.2.100"
k8sServicePort: 6443
kubeProxyReplacement: true

envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

operator:
  replicas: 1
  rollOutPods: true
  prometheus:
    enabled: true
    metricsService: true
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  metricsService: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

hubble:
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - hubble.lan
      pathType: ImplementationSpecific
