---
k8sServiceHost: "192.168.2.100"
k8sServicePort: 6443
kubeProxyReplacement: true

envoy:
  enabled: true

operator:
  replicas: 1
  rollOutPods: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - hubble.kube

# l2announcements:
#   enabled: true

# Commenting it out to enable Cilium to work over VPN
# devices: "wlan0"

# bgpControlPlane:
#   enabled: true

# externalIPs:
#   enabled: true

# l7Proxy: true
