k8sServiceHost: "192.168.2.100"
k8sServicePort: 6443
kubeProxyReplacement: true
envoy:
  enabled: true
operator:
  replicas: 1
ingressController:
  enabled: true
  service:
    loadBalancerIP: 192.168.2.250
l2announcements:
  enabled: true
externalIPs:
  enabled: true
