---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # NOTE: The path is relative to "app-of-apps/kustomization.yaml"
  # App of Apps
  - ../argo-apps/app-of-apps/app-of-apps.yaml
  # ArgoCD
  - ../argo-apps/argocd/argocd.yaml
  # Cilium
  - ../argo-apps/cilium/cilium.yaml
  # External DNS
  - ../argo-apps/external-dns/external-dns.yaml
  # Longhorn
  - ../argo-apps/longhorn/longhorn.yaml
  # Nginx Ingress
  - ../argo-apps/ingress-nginx/ingress-nginx.yaml
  # MetalLB
  - ../argo-apps/metallb/metallb.yaml
  # Kube Prometheus Stack
  - ../argo-apps/kube-prometheus-stack/kube-prometheus-stack.yaml
  # OpenCost
  - ../argo-apps/opencost/opencost.yaml
