---
services:
  ollama:
    image: ollama/ollama:0.3.6
    container_name: ollama
    hostname: pi
    tty: true
    restart: unless-stopped
    networks:
      - homelab
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2'
          memory: 4G
    volumes:
      - ollama:/root/.ollama
    
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    hostname: pi
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    depends_on:
      - ollama
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gpt.service=gpt"
        - "traefik.http.routers.gpt.rule=Host(`gpt.lan`)"
        - "traefik.http.services.gpt.loadbalancer.server.port=8080"
        - "traefik.http.routers.gpt.entrypoints=web"
    volumes:
      - open-webui:/app/backend/data

networks:
  homelab:
    external: true

volumes:
  ollama: {}
  open-webui: {}