{
 "title": "Bind",
 "description": "Bind9 DNS Service Statistics.",
 "tags": [
  "bind",
  "dns",
  "bind-exporter",
  "prometheus"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(bind_up, job)" } },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(bind_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - max(bind_boot_time_seconds{instance=~\"$node\"}) "
    }
   ]
  },
  {
   "title": "Reconfigured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - max(bind_config_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Named CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{instance=~\"$node\", job=\"$job\"}[120s])"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance=~\"$node\"}[120s])) by (mode) * 100) / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=~\"$node\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node.*\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
     "legendFormat": "Mem Free"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_query_duplicates_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "increase(bind_query_errors_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ error }}"
    },
    {
     "expr": "increase(bind_query_recursions_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "Recursions"
    }
   ]
  },
  { "title": "Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Incoming Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Request Opcodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_incoming_requests_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ opcode }}"
    }
   ]
  },
  {
   "title": "Response Results",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_responses_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  { "title": "Resolver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Resolver Response Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_response_errors_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_response_lame_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / LAME"
    },
    {
     "expr": "increase(bind_resolver_response_mismatch_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / MISMATCH"
    },
    {
     "expr": "increase(bind_resolver_response_truncated_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / TRUNCATED"
    }
   ]
  },
  {
   "title": "Resolver Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_queries_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_query_errors_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_query_edns0_errors_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / EDNS0"
    },
    {
     "expr": "increase(bind_resolver_query_retries_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / Retry"
    }
   ]
  },
  {
   "title": "Query By Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_query_duration_seconds_bucket{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ le }}"
    }
   ]
  },
  {
   "title": "Resolver Cache RR Sets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bind_resolver_cache_rrsets{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "DNSSEC Validation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_dnssec_validation_errors_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / ValErr"
    },
    {
     "expr": "increase(bind_resolver_dnssec_validation_success_total{instance=\"$node\",job=\"$job\"}[120s])",
     "legendFormat": "{{ view }} / {{ result }}"
    }
   ]
  }
 ]
}