{
 "title": "Smokeping",
 "tags": [ "smokeping" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "target",
    "query": {
     "query": "label_values(smokeping_response_duration_seconds_bucket, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Is up",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(host) (rate(smokeping_response_duration_seconds_bucket{host=~\"$target\", le=\"6.5536\"}[5m])) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Smoke Ping - $target",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(smokeping_response_duration_seconds_bucket{host=~\"$target\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency - $target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "smokeping_response_duration_seconds_sum{host=~\"$target\"} / smokeping_response_duration_seconds_count{host=~\"$target\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Packet Loss - $target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(smokeping_requests_total{host=~\"$target\"} - smokeping_response_duration_seconds_count{host=~\"$target\"})/smokeping_requests_total{host=~\"$target\"} ",
     "legendFormat": "{{host}} %"
    },
    {
     "expr": "(smokeping_requests_total{host=~\"$target\"} - smokeping_response_duration_seconds_count{host=~\"$target\"})",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}