---
cronjob:
  schedule: '*/30 * * * *'
  timeZone: 'Asia/Kolkata'

renovate:
  persistence:
    cache:
      enabled: true
      storageClass: "openebs"
      # -- Storage size of the cache PVC
      storageSize: "512Mi"
  config: |
    {
      
    }