---
services:
  whoami:
    image: traefik/whoami:v1.10.3
    container_name: "simple-service"
    hostname: pi
    networks:
      - homelab
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80/ || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.service=whoami"
        - "traefik.http.routers.whoami.rule=Host(`whoami.lan`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.entrypoints=web"

networks:
  homelab:
    external: true
