---
services:
  loki:
    image: grafana/loki:v3.3.2
    container_name: loki
    hostname: pi
    restart: always
    command:
      - "-config.file=/etc/loki/config.yaml"
    networks:
      - homelab
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    volumes:
      - ./config/:/etc/loki/

networks:
  homelab:
    external: true
