---
- name: Get latest Cilium CLI version
  ansible.builtin.uri:
    url: "https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt"
    return_content: true
  register: cilium_cli_version_raw

- name: Strip newline from Cilium version
  ansible.builtin.set_fact:
    cilium_cli_version: "{{ cilium_cli_version_raw.content | trim }}"

- name: Set architecture variable
  ansible.builtin.set_fact:
    cli_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Check if Cilium is already installed
  ansible.builtin.command: "cilium version --client"
  register: cilium_installed_version
  changed_when: false
  ignore_errors: true

- name: Download Cilium CLI
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-{{ cli_arch }}.tar.gz"
    dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    mode: '0644'
  when: cilium_cli_version not in cilium_installed_version.stdout

- name: Download Cilium CLI checksum
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    dest: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    mode: '0644'
  when: cilium_cli_version not in cilium_installed_version.stdout

- name: Verify checksum
  ansible.builtin.command:
    cmd: "sha256sum --check /tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
  args:
    chdir: /tmp
  register: checksum_result
  changed_when: false
  when: cilium_cli_version not in cilium_installed_version.stdout

- name: Install Cilium CLI
  ansible.builtin.unarchive:
    src: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true
    extra_opts: [--no-same-owner]
  when: cilium_cli_version not in cilium_installed_version.stdout
  notify: Cleanup temporary files
