---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: vault
spec:
  project: core
  sources:
    - repoURL: "https://github.com/bolleyboll/homelab.git"
      targetRevision: HEAD
      ref: myRepo
    - repoURL: "https://helm.releases.hashicorp.com"
      targetRevision: 0.30.0
      chart: vault
      helm:
        releaseName: vault
        valueFiles:
          - $myRepo/vault/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /spec/webhooks/0/clientConfig/caBundle

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Prune=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 3
