---
- name: Check if Docker CE is already Installed
  ansible.builtin.command: docker --version
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Set fact if Docker is installed
  ansible.builtin.set_fact:
    docker_installed: true
  when: docker_check.rc == 0

- name: Remove Conflicting Packages
  ansible.builtin.package:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Ensure Docker Dependencies are Installed
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true
  when: not docker_installed | default(false)

- name: Create Keyring Directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: not docker_installed | default(false)

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: not docker_installed | default(false)

- name: Add Docker repository
  ansible.builtin.template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
  when: not docker_installed | default(false)

- name: Update APT Package Cache
  ansible.builtin.apt:
    update_cache: true
  when: not docker_installed | default(false)

- name: Install Docker and Related Packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: not docker_installed | default(false)

- name: Ensure Docker Service is Started and Enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add bolleyboll user to the Docker group
  ansible.builtin.user:
    name: "bolleyboll"
    groups: docker
    append: true
