---
services:
  alloy:
    image: grafana/alloy:v1.5.1
    container_name: alloy
    hostname: pi
    restart: always
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    networks:
      - homelab
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80/ || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.alloy.service=alloy"
        - "traefik.http.routers.alloy.rule=Host(`alloy.lan`)"
        - "traefik.http.services.alloy.loadbalancer.server.port=12345"
        - "traefik.http.routers.alloy.entrypoints=web"
    volumes:
      - ./config/:/etc/alloy/

networks:
  homelab:
    external: true
