---
services:
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    hostname: pi
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yaml"
      - "--storage.path=/alertmanager"
    networks:
      - homelab
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:9093/-/ready || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 0
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.alertmanager.service=alertmanager"
        - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.lan`)"
        - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
        - "traefik.http.routers.alertmanager.entrypoints=web"
    volumes:
      - ./config/:/etc/alertmanager/

networks:
  homelab:
    external: true
