version: "3.8"
services:
  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    hostname: pi
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager/:/etc/alertmanager/
