---
injector:
  enabled: false

server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    pathType: ImplementationSpecific
    activeService: true
    hosts:
      - host: openbao.lan
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
    tls:
      - hosts:
          - openbao.lan
        secretName: openbao-tls

serverTelemetry:
  serviceMonitor:
    enabled: true
