---
injector:
  enabled: false

server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    pathType: ImplementationSpecific
    activeService: true
    hosts:
      - host: openbao.lan
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-issuer"
    tls:
      - hosts:
          - openbao.lan
        secretName: openbao-tls
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: openebs-hostpath
    accessMode: ReadWriteOnce
  readinessProbe:
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"

serverTelemetry:
  serviceMonitor:
    enabled: true
