lvm-localpv:
  analytics:
    enabled: false

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
    rawfile:
      # Disabled by default since rawfile is not marked as stable yet.
      enabled: false
  replicated:
    mayastor:
      enabled: false

loki:
  enabled: false

alloy:
  enabled: false
