lvm-localpv:
  localpv:
    basePath: "/var/openebs/localpv"

  hostpathClass:
    name: openebs
    isDefaultClass: true
    ext4Quota:
      enabled: false

  analytics:
    enabled: true

engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: false
    rawfile:
      # Disabled by default since rawfile is not marked as stable yet.
      enabled: false
  replicated:
    mayastor:
      enabled: false

loki:
  enabled: false

alloy:
  enabled: false
