---
services:
  authelia:
    container_name: 'authelia'
    hostname: pi
    image: authelia/authelia:4.38.18
    restart: 'unless-stopped'
    networks:
      - homelab
    environment:
      - TZ=Asia/Kolkata
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authelia.service=authelia"
        - "traefik.http.routers.authelia.rule=Host(`authelia.lan`)"
        - "traefik.http.services.authelia.loadbalancer.server.port=9091"
        - "traefik.http.routers.authelia.entrypoints=websecure"
    volumes:
      - ./config/:/config/
      - ./secrets/:/secrets/

networks:
  homelab:
    external: true
