---
services:
  authelia:
    container_name: 'authelia'
    hostname: pi
    image: authelia/authelia:4.38.10
    restart: 'unless-stopped'
    networks:
      - homelab
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Kolkata
      - AUTHELIA_LOG_LEVEL=info
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE='/secrets/JWT_SECRET'
      - AUTHELIA_SESSION_SECRET_FILE='/secrets/SESSION_SECRET'
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE='/secrets/STORAGE_PASSWORD'
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE='/secrets/STORAGE_ENCRYPTION_KEY'
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authelia.service=authelia"
        - "traefik.http.routers.authelia.rule=Host(`authelia.lan`)"
        - "traefik.http.services.authelia.loadbalancer.server.port=9091"
        - "traefik.http.routers.authelia.entrypoints=web"
    volumes:
      - ./config/:/config/
      - ./secrets/:/secrets/

networks:
  homelab:
    external: true
