---
services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    hostname: pi
    user: root
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - homelab
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "prometheus-job=prometheus"
        - "prometheus-port=9090"
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.service=prometheus"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.lan`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
        - "traefik.http.routers.prometheus.entrypoints=web"
    volumes:
      - ./config/:/etc/prometheus/
      - prometheusdata:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  homelab:
    external: true

volumes:
  prometheusdata:
