version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    hostname: pi
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - /home/pi/vol-mount/prometheus_data:/prometheus
