services:
  pihole:
    container_name: pihole
    hostname: pi
    image: pihole/pihole:2024.05.0
    restart: unless-stopped
    environment:
      TZ: "Asia/Kolkata"
      WEB_PORT: 8081
      FTLCONF_LOCAL_IPV4: "127.0.0.1"
      WEBPASSWORD: password
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "8081:80/tcp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.service=pihole-http"
      - "traefik.http.routers.pihole.rule=Host(`pihole.lan`)"
      - "traefik.http.services.pihole-http.loadbalancer.server.port=8081"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.piholedns.service=pihole-dns"
      - "traefik.http.routers.piholedns.rule=Host(`pihole-dns.lan`)"
      - "traefik.http.services.pihole-dns.loadbalancer.server.port=5353"
      - "traefik.http.routers.pihole-dns.entrypoints=web"
    # volumes:
    #   - "/home/pi/vol-mount/etc-pihole:/etc/pihole"
    #   - "/home/pi/vol-mount/etc-dnsmasq.d:/etc/dnsmasq.d"
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities

networks:
  ingress:
    external: true
