---
services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:9.0.2
    container_name: forgejo
    hostname: pi
    restart: unless-stopped
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - FORGEJO__database__DB_TYPE=${FORGEJO__database__DB_TYPE}
      - FORGEJO__database__HOST=${FORGEJO__database__HOST}
      - FORGEJO__database__NAME=${FORGEJO__database__NAME}
      - FORGEJO__database__USER=${FORGEJO__database__USER}
      - FORGEJO__database__PASSWD=${FORGEJO__database__PASSWD}
    networks:
      - homelab
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3000/api/healthz || exit 1"]
      start_period: 1m
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.forgejo.service=forgejo"
        - "traefik.http.routers.forgejo.rule=Host(`git.lan`)"
        - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
        - "traefik.http.routers.forgejo.entrypoints=web"
    volumes:
      - forgejodata:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:5.0.3
    container_name: forgejo-runner
    hostname: pi
    restart: unless-stopped
    user: 1000:1000
    command: '/bin/sh -c "sleep 5; forgejo-runner daemon"'
    networks:
      - homelab
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    volumes:
      - forgejorunnerdata:/data
      - /var/run/docker.sock:/var/run/docker.sock:rw

networks:
  homelab:
    external: true

volumes:
  forgejodata:
  forgejorunnerdata:
