services:
  traefik:
    image: traefik:v3.1.3
    container_name: traefik
    hostname: pi
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--providers.swarm.network=homelab"
      - "--providers.swarm.exposedbydefault=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--metrics.prometheus=true"
      - "--tracing=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - homelab
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.service=traefik"
        - "traefik.http.routers.traefik.rule=Host(`traefik.lan`)"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.entrypoints=web"
        - "prometheus-job=traefik"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  homelab:
    external: true
