services:
  traefik:
    image: traefik:v3.5.1
    container_name: traefik
    hostname: pi
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--providers.swarm.network=homelab"
      - "--providers.swarm.exposedbydefault=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--tracing.otlp=true"
      - "--tracing.otlp.grpc=true"
      - "--tracing.otlp.grpc.insecure=true"
      - "--tracing.otlp.grpc.endpoint=alloy:4317"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    networks:
      - homelab
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/ping || exit 1"]
    #   start_period: 1m
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "prometheus-job=traefik"
        - "prometheus-port=8082"
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.service=traefik"
        - "traefik.http.routers.traefik.rule=Host(`traefik.lan`)"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.entrypoints=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  homelab:
    external: true
