version: "3.8"
services:
  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    hostname: pi
    restart: unless-stopped
    env_file:
      - ./config/grafana/config.env
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - /home/pi/vol-mount/grafana_data:/var/lib/grafana
