---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    name: openldap
spec:
  project: core
  sources:
    - repoURL: "https://github.com/bolleyboll/homelab.git"
      targetRevision: HEAD
      ref: myRepo
    - repoURL: "https://start-codex.github.io/ldap-stack-helm-chart/"
      targetRevision: 1.4.2
      chart: ldap-stack
      helm:
        releaseName: openldap
        valueFiles:
          - $myRepo/openldap/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: openldap

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Prune=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 3
