---
ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
    - host: init.lan
      paths:
        - path: /
          pathType: ImplementationSpecific

securityContext:
  runAsNonRoot: false
  privileged: true
