---
- name: Cleanup Temporary Files
  ansible.builtin.file:
    path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz"
    state: absent

- name: Cleanup Checksum File
  ansible.builtin.file:
    path: "/tmp/cilium-linux-{{ cli_arch }}.tar.gz.sha256sum"
    state: absent
