---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.4.1-ce.0
    container_name: gitlab
    hostname: pi
    restart: unless-stopped
    networks:
      - homelab
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gitlab.service=gitlab"
        - "traefik.http.routers.gitlab.rule=Host(`git.lan`)"
        - "traefik.http.services.gitlab.loadbalancer.server.port=80"
        - "traefik.http.routers.gitlab.entrypoints=web"
    volumes:
      - ./config/gitlab.rb:/etc/gitlab/gitlab.rb
      - gitlabdata:/var/opt/gitlab
      - gitlabconfig:/etc/gitlab
      - gitlablogs:/var/log/gitlab

networks:
  homelab:
    external: true

volumes:
  gitlabdata:
  gitlabconfig:
  gitlablogs:
