---
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping:2.8.2
    container_name: smokeping
    hostname: pi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    restart: unless-stopped
    networks:
      - homelab
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.lan`)"
      - "traefik.http.services.smokeping.loadbalancer.server.port=80"
      - "traefik.http.routers.smokeping.entrypoints=web"

networks:
  homelab:
    external: true
