---
- name: Ensure GNU Stow is installed
  ansible.builtin.package:
    name: stow
    state: present

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest }}"
    update: true

- name: Stow all dotfiles
  ansible.builtin.command:
    cmd: "stow -d {{ dotfiles_dest }} -t {{ ansible_env.HOME }} ."
  register: stow_result

- name: Ensure zsh is installed
  ansible.builtin.package:
    name: zsh
    state: present

- name: Change default shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh

- name: Create .cache/zinit/completions directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.cache/zinit/completions"
    state: directory
    mode: '0755'
