---
services:
  bind9:
    image: xmrig:latest
    container_name: xmrig
    hostname: pi
    restart: always
    build:
      context: ./build/
      dockerfile: Dockerfile
    networks:
      - homelab
    deploy:
      mode: global

networks:
  homelab:
    external: true
