---
- name: Add Longhorn Helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: "{{ longhorn_namespace }}"
    create_namespace: true
    chart_version: "{{ longhorn_version }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
