---
- name: Add Cilium Helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: "{{ cilium_namespace }}"
    create_namespace: true
    chart_version: "{{ cilium_version }}"
    values:
      k8sServiceHost: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"
      k8sServicePort: 6443
      kubeProxyReplacement: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
