---
- name: Ensure k3s Config Directory Exists
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy k3s Master Config
  ansible.builtin.template:
    src: k3s_master_config.yaml.j2
    dest: "{{ k3s_master_config_path }}"
  notify: Restart k3s Service

- name: Install k3s Master
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -s - --config {{ k3s_master_config_path }} --token {{ vault_k3s_token }}
  args:
    creates: /etc/rancher/k3s/k3s.yaml

- name: Ensure k3s Service is Started and Enabled
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true
