---
- name: Check if Longhorn's Helm Release Exists
  kubernetes.core.helm_info:
    release_name: longhorn
    release_namespace: "{{ k3s_longhorn_namespace }}"
  register: longhorn_release_info
  failed_when: false
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Add Longhorn Helm Repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    force_update: true
  when: longhorn_release_info.status.chart is not defined

- name: Install Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: "{{ k3s_longhorn_namespace }}"
    create_namespace: true
    chart_version: "{{ k3s_longhorn_version }}"
  when: longhorn_release_info.status.chart is not defined
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
