---
- name: Ensure k3s config directory exists
  file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy k3s master config
  template:
    src: k3s_master_config.yaml.j2
    dest: "{{ k3s_master_config_path }}"
  notify: Restart k3s

- name: Install k3s master
  shell: |
    curl -sfL https://get.k3s.io | sh -s - --config {{ k3s_master_config_path }} --token {{ vault_k3s_token }}
  args:
    creates: /etc/rancher/k3s/k3s.yaml
