---
- name: Check if Cilium Helm Release Exists
  kubernetes.core.helm_info:
    release_name: cilium
    release_namespace: "{{ k3s_cilium_namespace }}"
  register: cilium_release_info
  failed_when: false
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Add Cilium Helm Repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io
    force_update: true
  when: cilium_release_info.status.chart is not defined

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: "{{ k3s_cilium_namespace }}"
    create_namespace: true
    chart_version: "{{ k3s_cilium_version }}"
    values:
      k8sServiceHost: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"
      k8sServicePort: 6443
      kubeProxyReplacement: true
  when: cilium_release_info.status.chart is not defined
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
