---
- name: Install k3s Agent
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -s - agent --server https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443 --token {{ vault_k3s_token }}
  args:
    creates: /etc/rancher/k3s/k3s.yaml

- name: Ensure k3s-agent Service is Started and Enabled
  ansible.builtin.service:
    name: k3s-agent
    state: started
    enabled: true
