version: "3.8"
services:
  nginx:
    image: nginx:1.25.3
    container_name: nginx
    hostname: pi
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    # Fix Volume Mounts
    volumes:
      - ./config/caddy:/etc/caddy/
