---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: custom-dashboards
    files:
      - dashboards/Bind.json
      - dashboards/cAdvisor_Docker-Insights.json
      - dashboards/cAdvisor.json
      - dashboards/Docker_Prometheus_Monitoring.json
      - dashboards/Node_Exporter.json
      - dashboards/Smokeping.json
      - dashboards/Traefik_Standalone.json
      - dashboards/Stock_Analysis.json
    options:
      labels:
        grafana_dashboard: "1"

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 77.6.2
    releaseName: "kube-prometheus-stack"
    namespace: monitoring
    valuesFile: values.yaml
