---
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - workflow.lan
    pathType: ImplementationSpecific
  authModes:
    - server

controller:
  metricsConfig:
    enabled: true
  telemetryConfig:
    serviceMonitor:
      enabled: true
