---
services:
  jenkins:
    image: jenkins/jenkins:2.442-jdk17
    container_name: jenkins
    hostname: pi
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/vol-mount/jenkins/:/var/jenkins_home/
