---
services:
  vault:
    image: hashicorp/vault:1.17.4
    container_name: vault
    hostname: pi
    restart: always
    environment:
      - VAULT_SKIP_VERIFY=true
      - TZ=Asia/Kolkata
    command:
      - "server"
    cap_add:
      - IPC_LOCK
    networks:
      - homelab
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vault.service=vault"
        - "traefik.http.routers.vault.rule=Host(`vault.lan`)"
        - "traefik.http.services.vault.loadbalancer.server.port=8200"
        - "traefik.http.routers.vault.entrypoints=web"
    volumes:
      - ./config:/vault/config/
      - vaultdata:/vault/files

networks:
  homelab:
    external: true

volumes:
  vaultdata:
