---
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    hostname: pi
    restart: always
    environment:
      VAULT_SKIP_VERIFY: true
    command:
      - "server"
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - ./config:/vault/config/
      - /home/pi/vol-mount/vault:/vault/files
