---
services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.109.0
    container_name: opentelemetry-collector
    hostname: pi
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - homelab
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.opentelemetry.service=opentelemetry"
        - "traefik.http.routers.opentelemetry.rule=Host(`opentelemetry.lan`)"
        - "traefik.http.services.opentelemetry.loadbalancer.server.port=55679"
        - "traefik.http.routers.opentelemetry.entrypoints=web"
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.61.0
    container_name: jaeger
    hostname: pi
    restart: always
    networks:
      - homelab
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jaeger.service=jaeger"
        - "traefik.http.routers.jaeger.rule=Host(`jaeger.lan`)"
        - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
        - "traefik.http.routers.jaeger.entrypoints=web"

networks:
  homelab:
    external: true
