---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    name: openbao
spec:
  project: core
  sources:
    - repoURL: "https://github.com/bolleyboll/homelab.git"
      targetRevision: HEAD
      ref: myRepo
    - repoURL: "https://openbao.github.io/openbao-helm"
      targetRevision: 0.27.1
      chart: openbao
      helm:
        releaseName: openbao
        valueFiles:
          - $myRepo/openbao/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: openbao

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Prune=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 3
