apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # NOTE: The path is relative to "app-of-apps/kustomization.yaml"
  # Project of Projects
  - ../argo-apps/app-of-projects/app-of-projects.yaml
  # core Project
  - ../argo-projects/core.yaml
