---
controller:
  logLevel: warn

speaker:
  logLevel: warn
  memberlist:
    mlBindPort: 7947

prometheus:
  rbacPrometheus: false
  serviceMonitor:
    enabled: true

frr-k8s:
  prometheus:
    serviceMonitor:
      enabled: true
