apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: ldap
spec:
  ingressClassName: nginx
  rules:
    - host: ldap.lan
      http:
        paths:
          - backend:
              service:
                name: lldap
                port:
                  name: ldap
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - ldap.lan
      secretName: ldap-tls
