FROM ubuntu:22.04

RUN curl -o actions-runner-linux-x64-2.312.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.312.0/actions-runner-linux-x64-2.312.0.tar.gz && \
    tar xzf ./actions-runner-linux-x64-2.312.0.tar.gz