---
- name: Ensure Helm CLI Dependencies are Installed
  ansible.builtin.package:
    name:
      - apt-transport-https
      - gnupg
      - curl
    state: present
    update_cache: true

- name: Detect System Architecture
  ansible.builtin.command: dpkg --print-architecture
  register: arch_result
  changed_when: false

- name: Check if Helm GPG key Exists
  ansible.builtin.stat:
    path: /usr/share/keyrings/helm.gpg
  register: helm_gpg_key

- name: Download Helm GPG key if missing
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /tmp/helm-signing.asc
    mode: "0644"
  when: not helm_gpg_key.stat.exists

- name: Convert Helm GPG key to dearmor if missing
  ansible.builtin.command:
    cmd: gpg --batch --yes --dearmor -o /usr/share/keyrings/helm.gpg /tmp/helm-signing.asc
  args:
    creates: /usr/share/keyrings/helm.gpg
  when: not helm_gpg_key.stat.exists

- name: Add Helm APT Repository
  ansible.builtin.template:
    src: helm-stable-debian.list.j2
    dest: /etc/apt/sources.list.d/helm-stable-debian.list
    owner: root
    group: root
    mode: "0644"
  register: repo_added

- name: Update-Package-Cache
  ansible.builtin.package:
    update_cache: true
  become: true

- name: Install Helm CLI using APT
  ansible.builtin.package:
    name: helm
    state: present
