---
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:5.1.1
    container_name: qbittorrent
    pull_policy: always
    hostname: docker
    networks:
      - servarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - qbittorrent-downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.37.0
    container_name: prowlarr
    hostname: docker
    pull_policy: always
    networks:
      - servarr
    depends_on:
      - qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.15
    container_name: sonarr
    hostname: docker
    pull_policy: always
    networks:
      - servarr
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - servarr-config:/config
      # Paths to Media
      - "/run/media/bolleyboll/Aman_HDD/Entertainment/TV Shows/:/tv"
      - "/run/media/bolleyboll/Aman_HDD/Entertainment/Anime/:/anime"
      - qbittorrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:5.26.2
    container_name: radarr
    hostname: docker
    pull_policy: always
    networks:
      - servarr
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - radarr-config:/config
      # Paths to Media
      - "/run/media/bolleyboll/Aman_HDD/Entertainment/Movies/:/movies"
      - qbittorrent-downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.5.2
    container_name: bazarr
    hostname: docker
    pull_policy: always
    networks:
      - servarr
    depends_on:
      - sonarr
      - radarr
      - qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - bazarr-config:/config
      # Paths to Media
      - "/run/media/bolleyboll/Aman_HDD/Entertainment/Anime/:/anime"
      - "/run/media/bolleyboll/Aman_HDD/Entertainment/Movies/:/movies"
      - "/run/media/bolleyboll/Aman_HDD/Entertainment/TV Shows/:/tv"
    ports:
      - 6767:6767
    restart: unless-stopped

  profilarr:
    image: santiagosayshey/profilarr:v1.0.1
    container_name: profilarr
    hostname: docker
    pull_policy: always
    networks:
      - servarr
    depends_on:
      - radarr
      - sonarr
    environment:
      - TZ=Asia/Kolkata
    ports:
      - 6868:6868
    volumes:
      - profilarr-config:/config
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:2.7.0
    container_name: jellyseerr
    hostname: docker
    pull_policy: always
    networks:
      - servarr
    depends_on:
      - radarr
      - sonarr
      - bazarr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - jellyseerr-config:/app/config
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:0.4.17-develop
    container_name: readarr
    hostname: docker
    pull_policy: always
    networks:
      - servarr
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - readarr-config:/config
      # Paths to Media
      # - /path/to/books:/books #optional
      # - /path/to/download-client-downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

networks:
  servarr:

volumes:
  qbittorrent-config:
    driver: local
  qbittorrent-downloads:
    driver: local
  prowlarr-config:
    driver: local
  servarr-config:
    driver: local
  radarr-config:
    driver: local
  bazarr-config:
    driver: local
  jellyseerr-config:
    driver: local
  profilarr-config:
    driver: local
  readarr-config:
    driver: local
