---
services:
  bind9:
    image: internetsystemsconsortium/bind9:latest
    container_name: bind9
    hostname: pi
    restart: always
    build:
      context: ./build/
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - homelab
    environment:
      - BIND9_USER=root
      - TZ=Asia/Kolkata
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bind.service=bind"
        - "traefik.http.routers.bind.rule=Host(`dns.lan`)"
        - "traefik.http.services.bind.loadbalancer.server.port=53"
        - "traefik.http.routers.bind.entrypoints=web"
        - "traefik.http.routers.bind-stats.service=bind-stats"
        - "traefik.http.routers.bind-stats.rule=Host(`dns-stats.lan`)"
        - "traefik.http.services.bind-stats.loadbalancer.server.port=8053"
        - "traefik.http.routers.bind-stats.entrypoints=web"

networks:
  homelab:
    external: true
