---
services:
  bind9:
    container_name: bind9
    hostname: pi
    build:
      context: ./build/
      dockerfile: Dockerfile
    image: internetsystemsconsortium/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Asia/Kolkata
    network_mode: host
    # volumes:
    #   - ./log/:/var/log/:rw
    restart: always
