---
services:
  bind9:
    container_name: bind9
    hostname: pi
    build:
      context: ./build/
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - BIND9_USER=root
      - TZ=Asia/Kolkata
    # volumes:
    #   - ./log/:/var/log/:rw
    restart: always
