---
services:
  bind9:
    container_name: bind9
    hostname: pi
    build:
      context: ./build/
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - BIND9_USER=root
      - TZ=Asia/Kolkata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bind.service=bind"
      - "traefik.http.routers.bind.rule=Host(`dns.lan`)"
      - "traefik.http.services.bind.loadbalancer.server.port=53"
      - "traefik.http.routers.bind.entrypoints=web"
    # volumes:
    #   - ./log/:/var/log/:rw
    restart: always
