---
rpi5:
  hosts:
    pi5.lan:
      ansible_host: 192.168.2.100
      ansible_user: bolleyboll

rpi3:
  hosts:
    pi3.lan:
      ansible_host: 192.168.2.101
      ansible_user: bolleyboll

homelab:
  children:
    rpi5:
    rpi3:

master:
  children:
    rpi5:

worker:
  children:
    rpi3:

k3s:
  children:
    master:
    worker:
