---
- name: Update Packages
  hosts: homelab
  become: true
  tasks:
    - name: Update Packages
      become: true
      ansible.builtin.package:
        upgrade: true
        update_cache: true

- name: Install Necessary Packages
  hosts: homelab
  become: true
  tasks:
    - name: Install Necessary Packages
      become: true
      ansible.builtin.package:
        name:
          - htop
          - btop
          - rsync
          - zsh
          - wget
          - curl
          - git
          - vim
          - neofetch
          - fzf
          - zoxide
          - lm-sensors
          - open-iscsi
          - netcat-traditional
          - jq
          - net-tools
        state: present

- name: Manage dotfiles using GNU Stow
  hosts: homelab
  become: false
  vars:
    dotfiles_repo: "https://github.com/bolleyboll/dotfiles"
    dotfiles_dest: "{{ ansible_env.HOME }}/dotfiles"
  roles:
    - dotfiles

- name: Install Cilium CLI
  hosts: homelab
  become: true
  roles:
    - cilium_cli

- name: Install Helm
  hosts: homelab
  become: true
  roles:
    - helm_cli

- name: Deploy K3s Cluster with Cilium
  hosts: k3s
  become: true
  vars:
    vault_k3s_token: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36303735336363303665643964376130326135313034613238633163313731303430396463303462
      6239313239353734336338643164333838353738303566370a316661396634376634376561346438
      66343365363933396366376537656539356535343364626563336562363538653862363361643963
      3365663866653632360a316662376135303165613636386336656232343361353866323532663738
      3166
  roles:
    - k3s

- name: Install Dockerd
  hosts: homelab
  become: true
  roles:
    - dockerd
