---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16-alpine
    container_name: uptime-kuma
    hostname: pi
    restart: always
    networks:
      - homelab
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.uptime.service=uptime"
        - "traefik.http.routers.uptime.rule=Host(`uptime.lan`)"
        - "traefik.http.services.uptime.loadbalancer.server.port=3001"
        - "traefik.http.routers.uptime.entrypoints=web"

networks:
  homelab:
    external: true
