version: "3.8"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11
    container_name: uptime-kuma
    hostname: pi
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./uptime-kuma:/app/data
