services:
  jobmanager:
    image: flink:1.20.1
    container_name: jobmanager
    hostname: pi
    restart: always
    networks:
      - homelab
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.flink.service=flink"
        - "traefik.http.routers.flink.rule=Host(`flink.lan`)"
        - "traefik.http.services.flink.loadbalancer.server.port=8081"
        - "traefik.http.routers.flink.entrypoints=web"

  taskmanager:
    image: flink:1.20.1
    container_name: taskmanager
    hostname: pi
    restart: always
    networks:
      - homelab
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 5
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  homelab:
    external: true
