services:
  jobmanager:
    image: flink:2.1.0
    container_name: jobmanager
    hostname: pi
    restart: always
    networks:
      - homelab
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.profiling.enabled: true
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.flink.service=flink"
        - "traefik.http.routers.flink.rule=Host(`flink.lan`)"
        - "traefik.http.services.flink.loadbalancer.server.port=8081"
        - "traefik.http.routers.flink.entrypoints=web"
        - "prometheus-job=flink-jobmanager"
        - "prometheus-port=9249"

  taskmanager:
    image: flink:2.1.0
    container_name: taskmanager
    hostname: pi
    restart: always
    networks:
      - homelab
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 5
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "prometheus-job=flink-taskmanager"
        - "prometheus-port=9249"

networks:
  homelab:
    external: true
