---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-haproxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    name: ingress-haproxy
spec:
  project: core
  sources:
    - repoURL: "https://github.com/bolleyboll/homelab.git"
      targetRevision: HEAD
      ref: myRepo
    - repoURL: "https://haproxy-ingress.github.io/charts"
      targetRevision: 0.16.1
      chart: haproxy-ingress
      helm:
        releaseName: haproxy-ingress
        valueFiles:
          - $myRepo/ingress-haproxy/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-haproxy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Prune=true
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 3
