---
services:
  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: node-exporter
    hostname: pi
    restart: always
    command:
      - "--web.listen-address=:80"
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.interrupts"
      - "--collector.lnstat"
      - "--collector.logind"
      - "--collector.meminfo_numa"
      - "--collector.mountstats"
      - "--collector.perf"
      - "--collector.processes"
      - "--collector.systemd"
      - "--collector.zoneinfo"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - homelab
    deploy:
      mode: global
      labels:
        - "prometheus-job=node-exporter"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro

networks:
  homelab:
    external: true
