---
targets:
- hosts:
  - youtube.com
  - facebook.com
  - google.com
  - twitter.com
  - linkedin.com
  - instagram.com
  - reddit.com
  - whatsapp.com
  - bseindia.com
  - nseindia.com
  - amngupta.com
  - blog.amngupta.com
  - pawandas.com
  - finance.yahoo.com
