---
targets:
- hosts:
  - youtube.com
  - facebook.com
  - google.com
  - twitter.com
  - linkedin.com
  - instagram.com
  - pinterest.com
  - reddit.com
  - tumblr.com
  - flickr.com
  - vimeo.com
  - iiitb.ac.in