---
title: "Odyssey"
subtitle: "Homer's"
documentTitle: "Sing a Song!"
logo: "assets/tools/logo.png"

header: true
footer: "Powered by Homer"

columns: "3"

connectivityCheck: true

proxy:
  useCredentials: false

defaults:
  layout: columns
  colorTheme: dark

services:
  - name: "Applications"
    icon: "fas fa-terminal"
    items:
      - name: "Adminer"
        logo: "assets/tools/adminer.png"
        subtitle: "Database UI"
        tag: "db"
        url: "http://adminer.lan/"
        target: "_blank"
      - name: "Smokeping"
        logo: "assets/tools/smokeping.png"
        subtitle: "Smokeping UI"
        tag: "network"
        url: "http://smokeping.lan/"
        target: "_blank"
      - name: "Gitea"
        logo: "assets/tools/gitea.png"
        subtitle: "Git"
        tag: "developement"
        url: "http://git.lan/"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Graphing Tool"
        tag: "dashboards"
        url: "http://charts.lan/"
        target: "_blank"
      - name: "Semaphore"
        logo: "assets/tools/semaphore.png"
        subtitle: "Semaphore UI"
        tag: "iac"
        url: "http://semaphore.lan/"
        target: "_blank"
      - name: "Uptime Kuma"
        logo: "assets/tools/uptimekuma.png"
        subtitle: "Uptime Monitor"
        tag: "uptime"
        url: "http://uptime.lan/"
        target: "_blank"
      - name: "Who Am I"
        logo: "assets/tools/whoami.png"
        subtitle: "WhoAmI"
        tag: "debug"
        url: "http://whoami.lan/"
        target: "_blank"
  - name: "Dashboards"
    icon: "fas fa-newspaper"
    items:
      - name: "Bind Dashboard"
        logo: "assets/tools/grafana.png"
        subtitle: "Bind Statistics"
        tag: "dashboards"
        url: "http://charts.lan/d/bind9-exporter/bind?orgId=1&refresh=5s"
        target: "_blank"
      - name: "cAdvisor Dashboard"
        logo: "assets/tools/grafana.png"
        subtitle: "cAdvisor Basic Statistics"
        tag: "dashboards"
        url: "http://charts.lan/d/pMEd7m0Mz/cadvisor?orgId=1&refresh=5s"
        target: "_blank"
      - name: "cAdvisor Insights Dashboard"
        logo: "assets/tools/grafana.png"
        subtitle: "cAdvisor Insights"
        tag: "dashboards"
        url: "http://charts.lan/d/ae3c41d7-cea5-4cca-a918-5708706b4d1a/cadvisor-docker-insights?orgId=1&refresh=5s"
        target: "_blank"
      - name: "Docker & Host Monitoring"
        logo: "assets/tools/grafana.png"
        subtitle: "Docker & Host Metrics"
        tag: "dashboards"
        url: "http://charts.lan/d/64nrElFml/docker-and-host-monitoring?orgId=1&refresh=5s"
        target: "_blank"
      - name: "Node Exporter"
        logo: "assets/tools/grafana.png"
        subtitle: "Node Exporter Metrics"
        tag: "dashboards"
        url: "http://charts.lan/d/rYdddlPWk/node-exporter?orgId=1&refresh=5s"
        target: "_blank"
      - name: "Smokeping"
        logo: "assets/tools/grafana.png"
        subtitle: "Smokeping Prober Metrics"
        tag: "dashboards"
        url: "http://charts.lan/d/isupaSmok/smokeping?orgId=1&refresh=5s"
        target: "_blank"
      - name: "Traefik"
        logo: "assets/tools/grafana.png"
        subtitle: "Traefik Standalone Dashboard"
        tag: "dashboards"
        url: "http://charts.lan/d/n5bu_kv45/traefik-dashboard?orgId=1&refresh=5s"
        target: "_blank"
  - name: "Metrics & Alerting"
    icon: "fas fa-bar-chart"
    items:
      - name: "Prometheus"
        logo: "assets/tools/prometheus.png"
        subtitle: "Metrics Server"
        tag: "metrics"
        tagstyle: "is-success"
        url: "http://prometheus.lan/"
        target: "_blank"
      - name: "Alertmanager"
        logo: "assets/tools/alertmanager.png"
        subtitle: "Alerting UI"
        tag: "alerting"
        url: "http://alertmanager.lan/"
        target: "_blank"
  - name: "Networking Shenanigans"
    icon: "fas fa-network-wired"
    items:
      - name: "Router"
        logo: "assets/tools/tplink.png"
        subtitle: "Router Web UI"
        tag: "router"
        tagstyle: "is-success"
        url: "http://router.lan/"
        target: "_blank"
      - name: "Traefik"
        logo: "assets/tools/traefik.png"
        subtitle: "Traefik Proxy"
        tag: "proxy"
        url: "http://traefik.lan/"
        target: "_blank"
      - name: "Pi-hole"
        type: "PiHole"
        logo: "assets/tools/pihole.png"
        subtitle: "Pihole Adblocker"
        tag: "adblock"
        tagstyle: "is-success"
        url: "http://pihole.lan/admin/"
        target: "_blank"
  - name: "Gods of the Cloud"
    icon: "fas fa-lock"
    items:
      - name: "Portainer"
        logo: "assets/tools/portainer.png"
        subtitle: "Container Management"
        tag: "container"
        url: "http://portainer.lan/"
        target: "_blank"
