---
# logLevel: debug

# sources:
#   - service
#   - ingress

# provider: rfc2136

# rfc2136:
#   host: "192.168.2.100"
#   zones:
#     - lan
#   tsigKeyName: rfc2136_tsig_secret
#   tsigSecretAlg: hmac-sha256
#   tsigSecret: "I13edEEt7kbt5GnlPvKsUpG1NayEGgWlI7XrMaYN9/I="

# metrics:
#   enabled: true
#   serviceMonitor:
#     enabled: true

---
logLevel: debug

deploymentStrategy:
  type: RollingUpdate

serviceMonitor:
  enabled: true

sources:
  - service
  - ingress

policy: upsert-only

provider:  # @schema type: [object, string]
  # -- _ExternalDNS_ provider name; for the available providers and how to configure them see [README](https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/README.md#providers).
  name: rfc2136
  webhook:
    image:
      # -- (string) Image repository for the `webhook` container.
      repository:  # @schema type:[string, null]; default: null
      # -- (string) Image tag for the `webhook` container.
      tag:  # @schema type:[string, null]; default: null
      # -- Image pull policy for the `webhook` container.
      pullPolicy: IfNotPresent
    # -- [Environment variables](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/) for the `webhook` container.
    env: []
    # -- Extra arguments to provide for the `webhook` container.
    args:
      - '--rfc2136-host=192.168.2.100'
      - '--rfc2136-port=53'
      - '--rfc2136-zone=lan'
      - '--rfc2136-min-ttl=0s'
      - '--rfc2136-tsig-axfr'
      - '--rfc2136-tsig-secret-alg=hmac-sha256'
      - '--rfc2136-tsig-keyname=rfc2136_tsig_secret'
      - '--rfc2136-tsig-secret=I13edEEt7kbt5GnlPvKsUpG1NayEGgWlI7XrMaYN9/I='
    # -- Extra [volume mounts](https://kubernetes.io/docs/concepts/storage/volumes/) for the `webhook` container.
    extraVolumeMounts: []
    # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) for the `webhook` container.
    resources: {}
    # -- [Pod security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container) for the `webhook` container.
    # @default -- See _values.yaml_
    securityContext: {}
    # -- [Liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) configuration for the `external-dns` container.
    # @default -- See _values.yaml_
    livenessProbe:
      httpGet:
        path: /healthz  # @schema type:[string, null]; default: null
        port: http-webhook  # @schema type:[integer,string]; default: string
      initialDelaySeconds: 10  # @schema type:[integer, null]; default: null
      periodSeconds: 10  # @schema type:[integer, null]; default: null
      timeoutSeconds: 5  # @schema type:[integer, null]; default: null
      failureThreshold: 2  # @schema type:[integer, null]; default: null
      successThreshold: 1  # @schema type:[integer, null]; default: null
    # -- [Readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) configuration for the `webhook` container.
    # @default -- See _values.yaml_
    readinessProbe:
      httpGet:
        path: /healthz  # @schema type:[string, null]; default: null
        port: http-webhook  # @schema type:[integer,string]; default: string
      initialDelaySeconds: 5  # @schema type:[integer, null]; default: null
      periodSeconds: 10  # @schema type:[integer, null]; default: null
      timeoutSeconds: 5  # @schema type:[integer, null]; default: null
      failureThreshold: 6  # @schema type:[integer, null]; default: null
      successThreshold: 1  # @schema type:[integer, null]; default: null
    service:
      # -- Webhook exposed HTTP port for the service.
      port: 8080
    # -- Optional [Service Monitor](https://prometheus-operator.dev/docs/operator/design/#servicemonitor) configuration for the `webhook` container.
    # @default -- See _values.yaml_
    serviceMonitor:
      interval:  # @schema type:[string, null]; default: null
      scheme:  # @schema type:[string, null]; default: null
      tlsConfig: {}
      bearerTokenFile:  # @schema type:[string, null]; default: null
      scrapeTimeout:  # @schema type:[string, null]; default: null
      metricRelabelings: []
      relabelings: []