---
services:
  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    hostname: pi
    restart: always
    command:
      - "-config.file=/etc/tempo/config.yaml"
    networks:
      - homelab
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:80/ || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    volumes:
      - ./config/:/etc/tempo/

networks:
  homelab:
    external: true
