---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - issuer.yaml
  - rfc2136-secret.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: 1.17.2
    releaseName: "cert-manager"
    namespace: cert-manager
    valuesFile: values.yaml
