---
services:
  redis-7:
    image: redis:7.4.2
    container_name: redis
    hostname: pi
    restart: always
    networks:
      - homelab
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.redis-7.service=redis-7"
        - "traefik.http.routers.redis-7.rule=Host(`redis-7.lan`)"
        - "traefik.http.services.redis-7.loadbalancer.server.port=6379"
        - "traefik.http.routers.redis-7.entrypoints=web"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

networks:
  homelab:
    external: true
