version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    hostname: pi
    restart: unless-stopped
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/pi
    ports:
      - 9000:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/vol-mount/dockge:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/pi:/home/pi
